### ISSUE TITLE
When running locally, Firefox shows invalid url

### ISSUE THREAD

**Issue by friedger** [stacks-network/sbtc-bridge-web#244]
When I try to run the bridge locally with `npm run tst`, I get the following error in Firefox:

```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:588:13)
    at file:///home/friedger/_repos/github/Stacks-Builders/sbtc-bridge-web/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:376:30
    at call (file:///home/friedger/_repos/github/Stacks-Builders/sbtc-bridge-web/node_modules/vite/dist/node/chunks/dep-75f53616.js:50564:7)
    at next (file:///home/friedger/_repos/github/Stacks-Builders/sbtc-bridge-web/node_modules/vite/dist/node/chunks/dep-75f53616.js:50508:5)
    at Function.handle (file:///home/friedger/_repos/github/Stacks-Builders/sbtc-bridge-web/node_modules/vite/dist/node/chunks/dep-75f53616.js:50511:3)
    at Server.app (file:///home/friedger/_repos/github/Stacks-Builders/sbtc-bridge-web/node_modules/vite/dist/node/chunks/dep-75f53616.js:50376:37)
    at Server.emit (node:events:512:28)
    at parserOnIncoming (node:_http_server:1067:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by friedger** [comment]
Resolved by now.
